AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sqs-lambda-test

  Sample SAM Template for sqs-lambda-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 128
  

Resources:
  SQSLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction/target/HelloWorld-1.0.jar
      Handler: helloworld.SQSLambdaHandler::handleRequest
      Runtime: java11
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: TestQueue.Arn

  TestQueue:
    Type: AWS::SQS::Queue

